packages:
  - "packages/*"
  - "workers/*"
  - "gateway"
  - "lambda/*"
  - "demo"
  - "tools/smoke-tests"
  - "tools/provisioning"
  - "tools/sign"
  - "tools/funding"
  - "tools/integration-tests"
  - "tools/onboard"
  - "apps/frontend"
