export { runOnboard } from './orchestrator.js'
export type { OnboardArgs, OnboardResult, OnboardStep, OnboardEnv, StepId } from './types.js'
export * as mintSubname from './steps/mint-subname.js'
export * as deploySplitter from './steps/deploy-splitter.js'
export * as registerAgentId from './steps/register-agent-id.js'
export * as setEnsRecords from './steps/set-ens-records.js'
export * as seedGateway from './steps/seed-gateway.js'
